blank_issues_enabled: false
contact_links:
  - name: Mkdirs Community Support
    url: https://github.com/MkdirsHQ/mkdirs-template/discussions
    about: Please ask and answer questions here.
  - name: Mkdirs Documentation
    url: https://docs.mkdirs.com
    about: Please check out the documentation here.
  - name: Mkdirs Video Tutorials
    url: https://www.youtube.com/@MkdirsHQ
    about: Please check out the video tutorials here.
